### PR TITLE
Update to Kallichore 0.1.9

### PR DESCRIPTION
**Pull request by jmcphers**
This change updates Positron to use 0.1.9 of the Kallichore supervisor. This update includes the following features:

- Rework "start kernel" RPC to not return until kernel has actually started, and include stderr/stdout if it fails to start or connect. Addresses #4960. 
- Busy/idle time reporting, intended for use in Posit Workbench.
- 20 second timeout to avoid hanging when waiting for a ZeroMQ socket connect.
- Bearer token auth; RPCs that change state now check the token (already supplied by Positron). 

### QA Notes

This is mostly internal improvements; #4690 has an example that can be used to create startup failures.

### CODE REVIEW

**Review by sharon-wang — COMMENTED** [review]
I was able to reproduce by uninstalling (`rig rm`) a version of R that Positron had already detected, then trying to start the R interpreter I just removed.

https://github.com/user-attachments/assets/468e7cd9-227e-453a-98e4-8207878f22f7

Note that I had to click the interpreter twice: the first time it stopped the current interpreter, the second time it started the selected interpreter.

I was still able to interact with the Console which was a bit confusing, but after a bit I got the following modal:

image

Upon clicking "Force Quit" it seems I got into a weird state in the UI:

image

But after selecting a valid interpreter, all was well again!

**Comment by jmcphers** [comment]
Converting to draft until I thoroughly investigate the experience @sharon-wang reported.

**Comment by jmcphers** [comment]
OK, it was kind of annoying but I decided to rev the backend again to provide more structure for the error. Now the backend returns the exit code, error message (if any), and the stderr/stdout contents if the startup fails, all in separate fields. We trap these structured errors on the frontend and use them to cue the right UI treatment. 

Note that messages emitted during startup (and the error) won't be red any more since they are emitted pre-startup. We could change that but I'm not sure making these red is any better (LMK if you disagree).

**Review by sharon-wang — COMMENTED** [review]
#### Start a deleted runtime
https://github.com/user-attachments/assets/4184f14d-6fc0-440c-a3b0-fe555b062b36
- It may be less immediately obvious that an error occurred since there isn't red text, but now that you can't type in the console, paired with the error message, I think it's clear that something went wrong!
- Based on user feedback we may want: red text on the error; guidance on what to do next, e.g. try starting a different interpreter / link to docs
- Something I noticed which I can file as a separate issue if preferred: it takes 2 clicks to start a runtime from the dropdown as it looks like we hit an error right after shutting down the current runtime, causing us to not start the selected runtime. On the second click, we start the runtime successfully.
   ```
   [2024-10-15T14:10:02Z ERROR kcserver::client_session] Failed to parse Jupyter message: EOF while parsing a value at line 1 column 0. Raw message: ""
   [2024-10-15T14:10:02Z ERROR kcserver::client_session] No data 
   from websocket
   ```

#### Runtime version mismatch in UI
https://github.com/user-attachments/assets/4cc361fa-37a9-4b30-b2d9-0cb886054485
- a UI bug (maybe to file separately?): when the startup error occurs, it looks like we can get a mismatch in the UI between the previous runtime (`4.3.3`) and the runtime that failed to start (`4.5.0`) in the runtime dropdown for the Console and the interpreter dropdown

**Comment by jmcphers** [comment]
@sharon-wang I fixed the bug with requiring two clicks to switch versions, thanks for catching that! I think the remainder can be tracked as separate work items but LMK if you disagree.

**Review by sharon-wang — APPROVED** [review]
LGTM!

I've tested the latest changes and no longer need to click twice to switch the interpreter 🙌 

I'll file a separate issue for the runtime version UI mismatch 👍 

- Update: opened https://github.com/posit-dev/positron/issues/5049

**Pull request merged**
