### PR TITLE
Use automattic slack reporter for tests

### PR DESCRIPTION
**Pull request by testlabauto**
Using the automattic slack reporter in place our the previous custom one.  Benefits:
* unit test failures will also be reported
* same reporter python tests are using
* more concise format that also links to commit

Also bumping smoke test workflows to use ubuntu-latest-4x

### QA Notes

Test failures properly reported

### CODE REVIEW

**Comment by midleman** [comment]
Any noticeable difference with overall time or test stability with upgrading to `ubuntu-latest-4x`?

**Comment by testlabauto** [comment]
> Any noticeable difference with overall time or test stability with upgrading to `ubuntu-latest-4x`?

I wish I could say yes.  That should maybe be pulled out.  Or we can leave it and continue to observe.  I am on the fence.

**Comment by jonvanausdeln** [comment]
I say leave it for now. Get a larger sample size.

**Review by jonvanausdeln — APPROVED** [review]
LGTM!

**Review by midleman — APPROVED** [review]
🚢

**Pull request merged**
