### PR TITLE
Draft: Generic "Run app" framework

### PR DESCRIPTION
**Pull request by seeM**
The purpose of this draft PR is to gather feedback about a generic approach to support a bunch of Python app frameworks. Feedback about code details isn't needed at this stage. You should be able to open a Shiny, Dash, Gradio, Streamlit, Flask, or FastAPI app and run it with the corresponding command. I haven't hooked up `when` clauses to only show the relevant command.

The idea is to allow extensions to register "application runners", implementing a `getRunOptions` method that returns the terminal command and set of environment variables needed to run an application, given some required information. The implementation of the `runApplication` method was adapted from the shiny-vscode extension.

In hindsight, I think the "application runner" concept is unnecessary at this stage. It's already possible to do all of this in extension land (e.g. shiny-vscode). I'm now leaning toward moving all of the logic into the Python extension. That'd mean duplicating code across extensions for different language packs, but I don't think that's a problem.

Before I make any further changes, what do folks think?

### CODE REVIEW

**Comment by seeM** [comment]
One more thing. The approach of finding a free port and passing it as a command-line arg doesn't work if the user hardcodes the port in their application, which is possible in some of these frameworks.

In those cases it would have still been possible to determine the port by scraping the terminal. However, I don't think that would helpful for Workbench, where I think we have to configure the app framework to use a URL prefix that depends on the port. Determining the port from the terminal would be too late.

**Comment by isabelizimm** [comment]
> It's already possible to do all of this in extension land (e.g. shiny-vscode). I'm now leaning toward moving all of the logic into the Python extension.

I don't feel _super_ strongly about this, but if it is equal convenience/difficulty in either location, I would rather have it in Positron core. I imagine it would be more convenient there (especially if UI elements change later or anything like that).

**Comment by juliasilge** [comment]
I took a look at what is here so far and I tend to think that it is better not to build out the application runner infrastructure into the Positron core without a motivating example, given that extensions can already provide tasks or run things in the terminal. Maybe we can outline what we would do instead:

- Use context keys to identify apps
- Provide command + UI for users to use
- Build out tasks (probably? could instead link up commands to directly run in terminal) to run the apps

There are a few other bits of this PR that we may still need to add to Positron itself, like finding a port.

**Comment by nstrayer** [comment]
What's here looks good to me. I haven't had time to fully consider the solution space but I like this. 

My vote would be keeping as much in core as possible to make it as easy as possible for new languages to be added. That being said this could be a massive instance of premature optimization so if the workload/ complexity is much less to put that logic into language packs then I will defer that decision to the implementer.

**Comment by isabelizimm** [comment]
adding some context on ports, from an offline discussion with @seeM 

possible ways to find if users have set ports themselves:

1. Looking for the argument `port=XXX` in a Python script (apparently this is one strategy workbench uses). People might not be using the named arg, which would make this difficult
2. Scraping the terminal, which might not be possible on workbench ❌ 
3. Watching for ports opened after starting the app. I'm not sure if there would be false positives here?
4. Not caring about the port, using our own. We can overwrite the user's port for all the frameworks besides gradio. The theory here is, for local dev/testing in the Viewer, the port is probably less important than in a production environment. However, this might be a confusing experience.

**Pull request closed without merging**
