### PR TITLE
Provide pipe and `<-` keyboard shortcuts in Quarto files, when RStudio Keymap is enabled

### PR DESCRIPTION
**Pull request by juliasilge**
### Intent

Addresses #1955 sort of but only in a half-hearted manner, by putting this in to the RStudio Keymap

### Approach

This feels a little bad because I'm putting the check for `config.rstudio.keymap.enable` in the ***Positron R*** extension rather than the RStudio Keymap extension. I did it this way because when one extension provides a command with a keybinding and a when clause, another extension can provide an additional when clause for that command, but only in an AND manner, not an OR manner. If you try to write out a boolean algebra expression for `editorLangId == r || editorLangId == quarto`, you have to put the check for the config where the command is contributed; otherwise it tries to check for `editorLangId == r && editorLangId == quarto` which of course is never true.

### QA Notes

- When you have the RStudio Keymap enabled, you can use the pipe and left assignment keyboard shortcuts in _both_ R files and Quarto files (including Python ones, unfortunately).
- When you have the RStudio Keymap not enabled, you can use the pipe and left assignment keyboard shortcuts only in R files, not in Quarto files.

None of this handles `.Rmd`

### CODE REVIEW

**Review by jmcphers — APPROVED** [review]
I think this is a fine stopgap to help folks who are using Positron more like RStudio.

It is sort of hard to tell what the logical statements do without squinting a bit. Maybe would be clearer to add this binding to the RStudio Keymap extension? Of course, that gives us the _opposite_ problem (now we're using commands rather than settings from another extension) but I think it'd read clearer.

**Comment by alearrigo** [comment]
Is this already live or is some extensions needed? It still doesn't work for me.

**Comment by anbrav0** [comment]
This also does not work for me as well , but I am assuming that this is still being worked on @alearrigo

**Comment by juliasilge** [comment]
For this to work well, you'll need:

- to have Quarto itself installed
- to have the Quarto VS Code extension installed in Positron

Screenshot 2024-06-30 at 2 38 49 PM


- to opt in to the RStudio Keymap in Settings

Screenshot 2024-06-30 at 2 39 48 PM

If you are sure you have all three of these set (Quarto installed, Quarto VS Code extension installed, RStudio Keymap turned _on_), can you open a new issue outlining the problems you observe?

**Comment by anbrav0** [comment]
@juliasilge This worked! thank you so much

**Pull request merged**
