### PR TITLE
Jonv-more-windows-tests

### PR DESCRIPTION
**Pull request by jonvanausdeln**
### Intent

Turns on more test in windows CI

### QA Notes
Passes in CI

### CODE REVIEW

**Review by midleman — APPROVED** [review]
Did you run just 1x or multiples? Just curious. :shipit:

**Review by testlabauto — APPROVED** [review]
LGTM!  Some long timeouts, but I think those cases have 2 mins to complete.

**Comment by jonvanausdeln** [comment]
> Did you run just 1x or multiples? Just curious. :shipit:

1x

**Comment by jonvanausdeln** [comment]
> LGTM! Some long timeouts, but I think those cases have 2 mins to complete.

Yeah... the venv starting takes long time now.. it even times out occasionally on Linux.

**Pull request merged**
