### PR TITLE
Project Wizard Smoke Tests: R Project with Renv Environment

### PR DESCRIPTION
**Pull request by sharon-wang**
## Description

- Addresses the "R Project with Renv Environment" part of https://github.com/posit-dev/positron/issues/3879

### Adds the following test cases for "R Project with Renv Environment":
- **Accept Renv install**: the user does not have renv installed, creates a new R Project with renv init selected and accepts to install it upon project creation
- **Renv already installed**: the user already has renv installed and creates a new R Project with renv init selected
- **Cancel Renv install**: the user does not have renv installed, creates a new R Project with renv init selected, but declines to install it upon project creation

### Introduces the following:
- adds `getPage()` to `PositronBaseElement`, which can be used to insert keyboard text to the page
- adds `getExplorerProjectFiles()` to `PositronExplorer`, which returns the top-level list of file and directory names showing in the explorer

## QA Notes

- Please fill in corresponding Test Ids :)

### CODE REVIEW

**Comment by jonvanausdeln** [comment]
These fail for me on Windows waiting for a response from the console:

image

**Comment by sharon-wang** [comment]
@jonvanausdeln I've added some handling to interact with the Console on Windows. I wonder if I'll also need to add a longer time for the `expect().toPass()` check for the renv-related files to show up, just in case the install takes a while?

**Review by jonvanausdeln — APPROVED** [review]
LGTM! Runs on windows without issue now!

**Comment by sharon-wang** [comment]
[CI passed](https://github.com/posit-dev/positron/pull/3881/checks?check_run_id=27210826396) for the 4 tests introduced. Running full smoke test suite to confirm the latest changes are working.

**Pull request merged**
