### PR TITLE
Updates to colorize-results for Positron Dark and Positron Light color themes

### PR DESCRIPTION
**Pull request by softwarenerd**
This PR fixes the `vscode-colorize-tests` [failure](https://positpbc.slack.com/archives/C07FR1JNZNJ/p1727065334878009) caused by the recent color theme updates made in https://github.com/posit-dev/positron/pull/4762.

In Positron, we ship with four color themes available to the user:

Positron Dark
Positron Light
Light High Contrast
Dark High Contrast

These color themes are defined in the following theme files:

```
positron_dark.json
        |_ dark_modern.json
                |_ dark_plus.json
                        |_ dark_vs.json

positron_light.json
        |_ light_modern.json
                |_ light_plus.json
                        |_ light_vs.json

hc_black.json
hc_light.json
```

The fix for the `vscode-colorize-tests` failure was to update all the `colorize-results` JSON files to only reference the four color themes that are visible to the user. For example:

```json
{
	"c": "<",
	"t": "text.html.derivative meta.embedded.block.html meta.tag.metadata.script.start.html punctuation.definition.tag.begin.html",
	"r": {
		"hc_black": "punctuation.definition.tag: #808080",
		"positron_dark": "punctuation.definition.tag: #808080",
		"positron_light": "punctuation.definition.tag: #800000",
		"hc_light": "punctuation.definition.tag: #0F4A85"
	}
},
```

### QA Notes

Tests should work now.

### CODE REVIEW

**Review by testlabauto — APPROVED** [review]
LGTM!

Thank you!

**Review by jonvanausdeln — APPROVED** [review]
LGTM!

**Comment by softwarenerd** [comment]
Full Test Suite was successful. Merging!

image

**Comment by timtmok** [comment]
During the 1.102.0 merge, it was discovered that running these tests updates the comparison files despite the failures. Inspecting the file shows that the changes look good and uses Positron's colours.

**Pull request merged**
