### PR TITLE
ci: add testrail back & test-full-suite fixes

### PR DESCRIPTION
**Pull request by midleman**
* Added back TestRail reporting. 
* Fixed an incorrect assertion in test.
* Full Test Suite workflow:
    * Fixed trigger for full test suite not working correctly.
    * Added option to NOT notify on slack (i hate spamming ppl in some cases!)

### QA Notes
* confirmed results upload to TR
* confirmed Full Suite triggers work now

### CODE REVIEW

**Comment by jonvanausdeln** [comment]
What was the change to `.secrets.baseline`?

**Comment by midleman** [comment]
> What was the change to `.secrets.baseline`?

I have no idea, when it tells me to update it I do. it is auto generated. 🤷‍♀️

**Review by jonvanausdeln — DISMISSED** [review]
LGTM! Just that one question about secrets file

**Review by testlabauto — DISMISSED** [review]
👍

**Pull request merged**
