### PR TITLE
Merge Kousa Dogwood Workbench extension bump to `1.5.20`

### PR DESCRIPTION
**Pull request by sharon-wang**
Bring in the Workbench extension version bump to `1.5.20` from: https://github.com/rstudio/vscode-server/pull/151.

### CODE REVIEW

**Comment by sharon-wang** [comment]
@cm421 would you mind commenting `I have read the CLA Document and I hereby sign the CLA` on this PR if you agree to the CLA?

**Comment by cm421** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sharon-wang** [comment]
Looking good on Ubuntu 24 :+1: 

`Posit Workbench 2024.12.0-daily+375.pro4, “Kousa Dogwood” (123323c8)`

image

**Review by cm421 — APPROVED** [review]
Testing the built-in extension v 1.5.20 in vscode looks good! It's ready to pull in once you're ready

**Pull request merged**
