### PR TITLE
Fix folding rules for R

### PR DESCRIPTION
**Pull request by juliasilge**
Addresses #4163 

I think those "region" folding rules must have never worked at all for R. With this, you will now see a folding UI affordance with code like this:

```r
# comment
# comment
# comment

# region I CAN WRITE ANYTHING HERE

1 + 1
lm(mpg ~ ., data = mtcars)

# endregion I CAN ALSO WRITE MORE HERE
```

You can either have `#region` or `# region`, with any other comment after that on the same line (but none before).

### QA Notes

With this change, we now get "Click to collapse the range", which we did not before:

Screenshot 2024-07-29 at 12 22 46 PM

### CODE REVIEW

**Comment by kevinushey** [comment]
Could this also support the RStudio-style section syntax? Where a section is denoted by a comment ending with `----`. (We also support `####` and `====`, but I think those are relatively less common?)

For reference: https://github.com/rstudio/rstudio/blob/6dc8162c6eb8a15ae43d8c6440b42cbd9db4f039/src/gwt/acesupport/acemode/r_highlight_rules.js#L912-L916

**Comment by juliasilge** [comment]
People also really want "sections" for their outline as described in https://github.com/posit-dev/positron/issues/3822, so I tend to think it will be better in the long run to have the LSP provide both of those consistently, both the symbols for the outline and [`textDocument/foldingRange`](https://microsoft.github.io/language-server-protocol/specification#textDocument_foldingRange); that way we can more easily keep those consistent and not maintain them in two separate ways.

**Review by kevinushey — APPROVED** [review]
LGTM!

I also had a comment about allowing for folding for RStudio-style sections (which end with `----`), but I'm not sure if this is something that can be expressed in the language-configuration JSON file, since a section marker can both open a new section, and implicitly close a previously-open section. (I'm also not sure if this handles nesting of sections; e.g. Markdown-style h1 and h2 sections?)

To wit, I guess (as Julia said) the LSP should probably be responsible for providing these?

**Comment by juliasilge** [comment]
Yes, I am pretty sure we need the LSP to provide those folding rules. Thank you @kevinushey!

**Pull request merged**
