### PR TITLE
Make summary stats, histogram, and frequency table `SupportStatus.Supported`, display sparkline histogram for `ColumnDisplayType.Number` data

### PR DESCRIPTION
**Pull request by softwarenerd**
**Data Explorer**

This PR changes the support status of `ColumnProfileType.SummaryStats`, `ColumnProfileType.Histogram`, and `ColumnProfileType.FrequencyTable` from `SupportStatus.Experimental` to `SupportStatus.Supported`.

Additionally, the first Data Explorer sparkline has been added. Sparkline histograms are now displayed for `ColumnDisplayType.Number` data.

image

### QA Notes

None

### CODE REVIEW

**Review by dfalbel — DISMISSED** [review]
LGTM! Works nice with R too when building Ark from https://github.com/posit-dev/ark/pull/458

image

**Comment by dfalbel** [comment]
Should the histograms be recomputed if you add a filter? They currently don't seem to change.

**Comment by softwarenerd** [comment]
> Should the histograms be recomputed if you add a filter? They currently don't seem to change. Actually, summary stats are not changed too.
> 
> From R, it looks like if you add a filter, the backend is receiving a request like this (with mtcars), and this request doesn't include the parameters for the histogram.
> 
> ```
> [Positron] SEND comm_msg to Shell: {"buffers":[],"content":{"comm_id":"c2c8e368-1111-47a0-9bb6-51001c6aa3cc","data":{"jsonrpc":"2.0","method":"get_column_profiles","params":{"profiles":[{"column_index":0,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":1,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":2,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":3,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":4,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":5,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":6,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":7,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":8,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":9,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":10,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]}],"format_options":{"large_num_digits":2,"small_num_digits":4,"max_integral_digits":7,"max_value_length":1000,"thousands_sep":","}}}},"header":{"msg_id":"b8985737-da00-42a1-86f6-f00d1efea42d","msg_type":"comm_msg","version":"5.0","date":"2024-08-16T01:51:09.532Z","session":"9d29589855f24503944adca3da9662f2","username":"dfalbel"},"metadata":{},"parent_header":{}}
> ```

I'm aware of this. Fix coming soon!

**Comment by softwarenerd** [comment]
> Should the histograms be recomputed if you add a filter? They currently don't seem to change. Actually, summary stats are not changed too.
> 
> From R, it looks like if you add a filter, the backend is receiving a request like this (with mtcars), and this request doesn't include the parameters for the histogram.
> 
> ```
> [Positron] SEND comm_msg to Shell: {"buffers":[],"content":{"comm_id":"c2c8e368-1111-47a0-9bb6-51001c6aa3cc","data":{"jsonrpc":"2.0","method":"get_column_profiles","params":{"profiles":[{"column_index":0,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":1,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":2,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":3,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":4,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":5,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":6,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":7,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":8,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":9,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]},{"column_index":10,"profiles":[{"profile_type":"null_count"},{"profile_type":"histogram"}]}],"format_options":{"large_num_digits":2,"small_num_digits":4,"max_integral_digits":7,"max_value_length":1000,"thousands_sep":","}}}},"header":{"msg_id":"b8985737-da00-42a1-86f6-f00d1efea42d","msg_type":"comm_msg","version":"5.0","date":"2024-08-16T01:51:09.532Z","session":"9d29589855f24503944adca3da9662f2","username":"dfalbel"},"metadata":{},"parent_header":{}}
> ```

OK, this should be fixed now.

**Comment by dfalbel** [comment]
Working great to me :) 

https://github.com/user-attachments/assets/169678ae-db27-4041-b74e-6d0ce6a20128

**Pull request merged**
