### PR TITLE
Fix R package installation commands after multiple restarts

### PR DESCRIPTION
**Pull request by jmcphers**
This change addresses the remainder of issue https://github.com/posit-dev/positron/issues/5532.

The underlying problem turned out to be that in some circumstances (depending on timing) it is possible to get two UI comms to open at the same time. This happens when the _Ready_ status arrives multiple times. Since the _Ready_ status triggers the creation of the UI comm, and creating the comm is an async operation, receiving it multiple times can result in multiple in-flight requests to create the comm.

The fix has a few parts:

1. The fact that the _Ready_ status event happens multiple times can be traced upstream to the supervisor, which can mark the kernel Ready after getting the kernel info _and_ after the initial heartbeat. This fix updates to version 0.21 of the supervisor, which doesn't have this bug.
2. Even if the runtime fires multiple _Ready_ events, we should not create multiple UI comms. This fix adds re-entrancy guards to the part of the system that creates the comm, so that if we are asked to create one when one is already active, or we are in the process of creating one, we don't wind up with two.
3. Finally, I've done some light refactoring of the active session state to reduce the size of the runtime session service, and added a test for this bug.

### QA Notes

In order to test this, you'll want to be sure that the scenario in #5532 works at least 5 times in a row. I also recommend enabling the Runtime Sessions debug panel so you can check to see that the correct number of UI comms are in play as you test.

### CODE REVIEW

**Comment by juliasilge** [comment]
> I also recommend enabling the Runtime Sessions debug panel so you can check to see that the correct number of UI comms are in play as you test.

I have a question for you about this, @jmcphers, because maybe I don't have the correct mental model of this debug panel.

I can make the `positron.ui` number here climb infinitely (???) high by executing code such as `devtools::test()` many times:

Screenshot 2024-12-03 at 1 33 51 PM

What does that number 30 there mean?

**Comment by jmcphers** [comment]
That `30` number isn't the number of UI comms -- there's still just one (correct!) in the screenshot. The counter is the number of messages that have flowed through the comm. Try resizing the console a few times and you should see it tick up as the new size is sent to the kernel.

**Comment by juliasilge** [comment]
> number of messages

Thank youuuuuu! I tried finding the original PR that implemented this panel but was not successful in finding this out on my own.

If I do "Reload Window" I get multiple of the different kinds of comms. Is that expected?

Screenshot 2024-12-03 at 2 01 32 PM

That will persist until I do a regular restart. After a regular restart (no window reload) I only get one of each. Since the original command that wasn't working involves a restart, I don't think this presents a problem for https://github.com/posit-dev/positron/issues/5532 specifically.

**Comment by jmcphers** [comment]
You're seeing https://github.com/posit-dev/positron/issues/1126, which we should totally fix but indeed isn't related to this bug.

**Review by juliasilge — APPROVED** [review]
This works great now. Thank you so much!

**Pull request merged**
