### PR TITLE
E2E tests: add pop out tests for plots to editor

### PR DESCRIPTION
**Pull request by testlabauto**
Just adding popout of plots to editor testing into existing plots tests suite.

Also, added code to clear clipboard after copying to it so tests do not interfere with each other.

Note that unit and integration time out problems fixed separately.

### QA Notes

All smoke tests should pass.

### CODE REVIEW

**Review by midleman — APPROVED** [review]
Should `closeAllEditors` be in the an afterEach hook?

**Comment by testlabauto** [comment]
> Should `closeAllEditors` be in the an afterEach hook?

well, only 3 cases out of 17 use it, so I was hesitant to add it there.

**Comment by testlabauto** [comment]
> well, only 3 cases out of 17 use it, so I was hesitant to add it there

well, only 3 cases out of 17 use it, so I was hesitant to add it there

**Comment by testlabauto** [comment]
> Should `closeAllEditors` be in the an afterEach hook?

well, only 3 cases out of 17 use it, so I was hesitant to add it there

**Pull request merged**
