### PR TITLE
Updates to the display of column profile summary stats

### PR DESCRIPTION
**Pull request by softwarenerd**
This PR updates the formatting and display of column summary stats. This work is being done so that we can re-enable the feature in an upcoming build.

Here's a movie of this PR in action:

https://github.com/user-attachments/assets/3dcb2bc1-79e8-405d-8c61-925b3998899c

### QA Notes

None.

### CODE REVIEW

**Review by dfalbel — DISMISSED** [review]
Adding some comments from slack:


I feel like the order of info for numeric columns should be min, median, mean, max, sd, missing:

image

I'd also remove the `mean` from date/datetime variables as I feel like this is very hard to have a useful interpretation.

**Comment by softwarenerd** [comment]
> Adding some comments from slack:
> 
> I feel like the order of info for numeric columns should be min, median, mean, max, sd, missing:
> 
> image
> 
> I'd also remove the `mean` from date/datetime variables as I feel like this is very hard to have a useful interpretation.

I've made the necessary adjustments.

image

**Comment by softwarenerd** [comment]
Final adjustments.

image

**Review by dfalbel — APPROVED** [review]
LGTM!

**Pull request merged**
