### PR TITLE
Fully interactive IPyWidgets

### PR DESCRIPTION
**Pull request by seeM**
This PR adds support for fully interactive IPyWidgets, addressing #3276.

For example, create and display a widget:

```python
import ipywidgets
w = ipywidgets.IntSlider()
display(w)
```

Interact with the widget in the UI, then check its value in the console:

```python
w.value
```

Set the value in the console:

```python
w.value = 13
```

Note the updated UI.

---

We've already been using VSCode notebook renderers to render interactive plots in the Plots pane. This PR adds a notebook renderer for IPyWidgets, and routes messages between the renderer (widget frontend) and the runtime (widget backend) via the updated Positron IPyWidgets service.

### Unit Tests

The new implementation of the IPyWidgets service is unit tested. This PR adds a few mocks to make that possible. Most useful are `TestLanguageRuntimeSession ` and `TestRuntimeClientInstance`, although they're only implemented as far as needed for this PR.

I used the convention of starting Positron test suites with `Positron - `. There's also a new script to run only Positron's unit tests excluding VSCode's:

```sh
./scripts/test-positron.sh
```

Note that this script is not included in our CI since we already run `./scripts/test.sh` which is a superset.

### QA Notes

These widgets/libraries should work:

* All of `ipywidgets` except `Output` and `Image`
* `ipytree`
* `ipyleaflet`
* `anywidget`
* `drawdata`
* `pythreejs`

These widgets/libraries will not yet work:

* `bqplot`
* `ipycanvas`
* `ipydatagrid`
* `ipympl`

Most of the remaining widgets/libraries require us to support `buffers` in the Jupyter messaging protocol (#3974) which I intend to work on next.

### CODE REVIEW

**Comment by nstrayer** [comment]
🙌 This is awesome. It's a big one so I'm going to tackle the review tomorrow morning! Excited about having this in!

**Review by nstrayer — DISMISSED** [review]
Looks good to me, although it's large enough I won't pretend I fully grasp how everything fits together! 
Just a few comments that are take-it-or-leave-it! 
Excited to have this!

**Review by isabelizimm — DISMISSED** [review]
Really great work! Mostly kicking the tires around; I checked against the widgets we had already supported as well (ipyleaflet, ipywidget, pythreejs) and all seemed to work!

I can't reproduce it, but the first time I tried out `pythreejs`, it look about 20 seconds to load the widget, and trying to run the same code twice crashed the entire Positron build? I *think* it was just a weird fluke since I restarted and no delay or crashing since, but noting here. This was the code I ran.

```{python}
from pythreejs import CircleGeometry

x = CircleGeometry(
     radius=10,
     segments=10,
     thetaStart=0.25,
     thetaLength=5.0)

display(x)
```

For your viewing pleasure, here's `drawdata`, which uses a widget powered by the `anywidget` framework (which seems to be supported now!!!), where you can draw data and then export it to a dataframe. Mostly adding since this was so much fun to play around with 😆 

https://github.com/user-attachments/assets/d0968792-77b9-4fde-af60-a68e5898d4c1

**Comment by seeM** [comment]
Thank you for the reviews! I've addressed all of the comments, will merge once CI passes 🎉

**Pull request merged**
