### PR TITLE
Stop the prompt from flickering when code is executed 

### PR DESCRIPTION
**Pull request by softwarenerd**
This PR addresses https://github.com/posit-dev/positron/issues/705 (prompt flickering) by adjusting the prompt to be spaces immediately after code is executed. This prevents the prompt from being displayed while code is executing, which was the cause of the flickering.

Prior to this PR, the Console prompt would noticeably flicker about 30% of the time. The sequence of distinct UI frames that lead to this flicking are:

1: User enters some code and executes it:

image

2: The `ConsoleInput` component gets the code from the `CodeEditorWidget`, creates the provisional `ActivityItemInput` component, then clears the `CodeEditorWidget`'s model.  This results in the following frame because the `CodeEditorWidget` renders the standard prompt too soon:

image

This is what causes the flicker because once the code executes, the result of the execution is displayed between the `ActivityItemInput` and the `CodeEditorWidget`:

image

### CODE REVIEW

**Review by seeM — DISMISSED** [review]
LGTM. I tested about 30 executions, and there's still one possible "flicker" rendering sequence that happened about once every 15 executions. This PR is definitely an improvement though.

Here's the incorrect sequence:

1. User enters some code and executes it:

    image

2. The `ConsoleInput` component clears the `CodeEditorWidget` model and makes the prompt blank. This results in an incorrect frame because the provisional `ActivityItemInput` is not yet rendered by React, even though the Monaco editor has  rendered:
    
    image

3. Now the `ActivityItemInput` is rendered.

    image

**Comment by softwarenerd** [comment]
> LGTM. I tested about 30 executions, and there's still one possible "flicker" rendering sequence that happened about once every 15 executions. This PR is definitely an improvement though.
> 
> Here's the incorrect sequence:
> 
> 1. User enters some code and executes it:
>     image
> 2. The `ConsoleInput` component clears the `CodeEditorWidget` model and makes the prompt blank. This results in an incorrect frame because the provisional `ActivityItemInput` is not yet rendered by React, even though the Monaco editor has  rendered:
>     image
> 3. Now the `ActivityItemInput` is rendered.
>     image

Thanks Wasim. I will investigate this and see if I can make the same thing happen.

**Comment by seeM** [comment]
@softwarenerd I tested some more on commit 6a6b77d. It still happens about 1 in 15 times on my laptop. Here's a clipped video – you'll have to scrub slowly or step through it with the keyboard:

https://github.com/user-attachments/assets/78934663-d1c5-4d1f-9ff6-9de74b59a406

I then tried updating the `codeExecute` callback to:

```typescript
						codeExecute={() => {
							console.log('--------------------------- CODE EXECUTE RENDER');
							flushSync(() => {
								this.forceUpdate(() => {
									console.log('--------------------------- CODE EXECUTE RENDERED');
								});
							});
						}}
```

And tested again on about 80 executions, and it seems to have totally fixed it! I also tested with just `forceUpdate` and no `flushSync` but that didn't fix it, both are necessary.

For reference, here's how I test. I press "up" and "enter" a bunch of times, then scrub through the video. Admittedly, this is a bit like DoSing our UI, but it does help to pick out these little issues:

https://github.com/user-attachments/assets/050bd9be-1b23-4d09-9868-58ffa7022d30

**Comment by seeM** [comment]
My understanding is: `this.render()` computes the new React node but doesn't do anything with it. `this.forceUpdate` tells React to internally call `this.render`, compare it with the DOM, and commit a DOM update. `flushSync` makes sure the DOM update is committed immediately and synchronously.

**Review by seeM — APPROVED** [review]
LGTM, thanks! I can confirm that this removes all flickering. I also tested activity item tracing, input prompts, send to console, and all continued to work as expected.

As mentioned on Slack, I think it might be fixable without a class component by wrapping `props.positronConsoleInstance.executeCode(code)` in a `flushSync`, but this branch definitely works as is so let's bring it in.

**Pull request merged**
